name: pure_live_chat
description: Realtime chatting system with audio and video streaming.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  rename: ^1.2.0

  #UI/UX
  flutter_spinkit: ^4.1.2+1
  loading_overlay: ^0.2.1

  #GetX
  get: ^3.17.1
  get_storage: ^1.3.2

  #network
  connectivity: ^0.4.4
  app_settings: ^4.0.4
  permission_handler: ^5.0.1+1
  flutter_local_notifications: ^3.0.2
  graphql_flutter: ^3.1.0
  agora_rtc_engine: ^1.0.15

  #Firebase
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_storage: ^5.2.0
  cloud_firestore: ^0.14.4


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: PottaOne-Regular
      fonts:
        - asset: assets/fonts/PottaOne-Regular.ttf
    - family: PermanentMarker-Regular
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
